version: "3"

services:
  mosquitto:
    image: sersenia/eclipse-mosquitto-no-auth
    ports:
      - 1883:1883
      - 8883:8883
    networks:
      - tracking_service_network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      # we copy our scripts onto the container
      - ./TrackingService/sql:/usr/src/app 
    # bash will be executed from that path, our scripts folder
    working_dir: /usr/src/app 
    # run the entrypoint.sh that will import the data AND sqlserver
    command: sh -c 'chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd
    
    networks:
       - tracking_service_network

  unittests:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    volumes:
      - ./:/code
    command: bash -c "sleep 25 && dotnet test /code/TrackingServiceTest/TrackingServiceTest.csproj"
    depends_on:
      - mssql
    networks:
       - tracking_service_network

networks:
  tracking_service_network:
     driver: bridge
