apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBCIyWl2hqHn2Z4H7PI24SM+v5OsRbIEKboMrQ1Dn0X0wrg9mEbaHgVn29DGsaW0f2FEwWElnhYQ11E8J9Fh+FZlm+aUAh53m2slltB9wqkKJgckE54+siGfp6HFm4FdqT4lXjJlwbGXfW+wT7wdAlVQOg0FwEZMdrsxn7fObhWirnIPXOonnFXZZ1hmyTAvHTyU+Q2hVXWSePaV7ajX+WMwQ+fVxtrMGXltoi+ffJg/z9649D9q9CKdvKDwJq0br0v8upCdUVPuv6RfcRNmQOz0CT1gQrzLFkXOcBBlu//+JeN17WIpIF+s/TLu6jXsrCSJmZ5NcsMUKQBWe3ogJZz3Me3oqYd0zHXhHIpGXwanUe5iy7Z3MCfM8a+pxotmf9EVRoWfI8LJ/+yNdfDQsoBuQGZHOBQuMK72L61ucOcehdiH2HbbGtAJWghXNrW+XiMPNb1sEvngOTbfBGFv0CjpC/0KLXC+39IIbHP6dP8qAx0ys4XkiNm3RQo1dJA7ORe1fUWYu4Ch3YDgfx+4i94UsqeTW/7lu36Q144DYKJezOivBIl6fc7wAfM40SHYZM/4UueFA2BfGLFOdZhJk+zsyTlmKWvFIRZmgyFuj3QskQG1kAOjNdrbiN4Dg7W1GUPRZgXlkYEsQrhYBSHAdFBfmL4ULSD4o1KaBqmMByLl2moUq5RB7zgPQgtOWLn6GWARfT0gAye1vym/AcUEXJaEnQQv89S3Hhznc9CKEd8pXVmEiaXAvDUhl7BwhwN8qLKN3nL9SpPg4nj/wOHvGAG24lXkWFblvJnzlCw3IRkkhD8hEIBz10YGxppBjXZXV52
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ .Release.Name }}-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson

