apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
spec:
  selector:
    app: mqtt
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 30001