name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2     

    - name: Fire docker
      run: docker-compose -f ${{ runner.workspace }}/${{ github.event.repository.name }}/docker-compose-test.yaml up --abort-on-container-exit --exit-code-from unittests

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: GitHub Container Registry Login
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./TrackingService/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/tracking-service:latest

  helm-lint:
  
    name: Helm lint and release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Helm Lint
        uses: WyriHaximus/github-action-helm3@master
        with:
          exec: helm lint ./helm-chart
      - name: Helm install
        uses: WyriHaximus/github-action-helm3@master
        with:
          exec: helm upgrade --install tracking-service ./helm-chart
          kubeconfig: '${{ secrets.KUBECONFIG }}'